[package]
name = "talk"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "daemon"
path = "src/daemon.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
anyhow = "1.0.62"
structopt = "0.3.26"
